import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState, useEffect, useRef } from "react";
import Welcome from "./Welcome";
import { User } from "../interfaces";
import Contacts from "./Contact";
import { getAllUsers, host } from "../api";
import { useRouter } from "next/router";
import ChatContainer from "./ChatContainer";
import { Socket, io } from "socket.io-client";
import dynamic from "next/dynamic";
import VideoCall from "./VideoCall";
import Peer from "peerjs";

export default function Home() {
  const [contacts, setContacts] = useState<User[]>([]);
  const [currentUser, setCurrentUser] = useState<User>();
  const [currentChat, setCurrentChat] = useState(undefined);
  const [accessToken, setAccessToken] = useState(undefined);
  const [isCall, setCall] = useState(false);
  const router = useRouter();
  const socket = useRef<Socket>();
  const myVideoRef = useRef();
  //   const [myVideoRef, setMyVideoRef] = useState(useRef()); //Your video
  const [peerVideoRef, setPeerVideoRef] = useState(useRef()); //The other users video
  const peerInstance = useRef();

  useEffect(() => {
    const setUser = async () => {
      if (!localStorage.getItem("user")) {
        router.replace("/login");
      } else {
        setCurrentUser(await JSON.parse(localStorage.getItem("user")!));
      }
    };
    setUser();
  }, [router]);

  useEffect(() => {
    if (currentUser) {
      socket.current! = io(`${host}?user_id=${currentUser.id}`, {
        transports: ["websocket"],
      });
    }
  }, [currentUser]);

  useEffect(() => {
    const setToken = async () => {
      if (!localStorage.getItem("accessToken")) {
        localStorage.removeItem("user");
        router.replace("/login");
      } else {
        setAccessToken(await JSON.parse(localStorage.getItem("accessToken")!));
      }
    };
    setToken();
  }, [router]);

  useEffect(() => {
    const getContacts = async () => {
      if (currentUser && accessToken) {
        const { data } = await getAllUsers(currentUser.id, accessToken);
        setContacts(data);
      }
    };
    getContacts();
  }, [currentUser, accessToken]);

  const handleChatChange = (chat: any) => {
    setCurrentChat(chat);
  };

  useEffect(() => {
    const peer = new Peer({
      host: "localhost",
      port: 9000,
      path: "/peer",
    });

    peer.on("open", (id) => {
      console.log(id);

      socket.current!.emit("peer-id", {
        peer_id: id,
        user_id: currentUser?.id,
      });
    });

    // peer.on("call", (call) => {
    //   var getUserMedia = navigator.mediaDevices.getUserMedia;
    //   getUserMedia({
    //     video: isVideo ? true : false,
    //     audio: isMic ? true : false,
    //   }).then((mediaStream) => {
    //     // myVideoRef.current = mediaStream;
    //     myVideoRef.current.srcObject = mediaStream;
    //     // myVideoRef.current.play();
    //     call.answer(mediaStream);
    //     call.on("stream", (peerStream) => {
    //       console.log(peerStream);
    //       peerVideoRef.current.srcObject = peerStream;
    //       // peerVideoRef.current.play();
    //     });
    //   });

    peerInstance.current! = peer;
  }, [currentUser?.id, socket]);

  return (
    <>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={!isCall ? styles.container : styles.containerCall}>
          {!isCall ? (
            <Contacts
              contacts={contacts}
              currentUser={currentUser}
              changeChat={handleChatChange}
            />
          ) : (
            <VideoCall
              currentChat={currentChat}
              currentUser={currentUser}
              accessToken={accessToken}
              socket={socket}
              isCall={isCall}
              setCall={setCall}
              myVideoRef={myVideoRef}
            />
          )}
          {currentChat === undefined ? (
            <Welcome currentUsername={currentUser?.username || ""} />
          ) : (
            <ChatContainer
              currentChat={currentChat}
              currentUser={currentUser}
              accessToken={accessToken}
              socket={socket}
              setCall={setCall}
              peerInstance={peerInstance}
              myVideoRef={myVideoRef}
              //   setMyVideoRef={setMyVideoRef}
            />
          )}
        </div>
      </main>
    </>
  );
}
