import { FormEvent, useState, useEffect, useRef } from "react";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { ToastOptions } from "react-toastify/dist/types";
import Image from "next/image";
import Link from "next/link";
import styles from "@/styles/Login.module.css";
import Head from "next/head";
import { useRouter } from "next/router";

export default function VideoCall() {
  const [errorSetting, seterrorSetting] = useState("");
  const myVideoRef = useRef(); //Your video
  const peerVideoRef = useRef(); //The other users video
  const myStreamRef = useRef(); //Our video stream
  const [done, setdone] = useState(false);

  const toastOptions: ToastOptions = {
    position: "bottom-right",
    autoClose: 8000,
    pauseOnHover: true,
    draggable: true,
    theme: "dark",
  };

  const router = useRouter();

  useEffect(() => {
    //Getting our Video and Audio
    navigator.mediaDevices
      .getUserMedia({
        audio: true,
        video: true,
      })
      .then((stream) => {
        myStreamRef.current = stream;
        //Storing our video
        myVideoRef.current.srcObject = stream;
      })
      .catch((err) => {
        /* handle the error */
        console.log(err);
      });
  }, []);
  return (
    <>
      <Head>
        <title>Video Call</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <video autoPlay ref={myVideoRef} muted playsInline width={"500px"} />
          <h1>User</h1>
        </div>
        <div>
          <video autoPlay ref={peerVideoRef} playsInline width={"500px"} />
          {done && <h1>Peer</h1>}
        </div>
        <h1>{errorSetting}</h1>
      </main>

      <ToastContainer />
    </>
  );
}
